# Generated by Django 4.1.3 on 2022-11-28 09:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=55, null=True)),
                ('country', models.CharField(max_length=70, null=True)),
                ('city', models.CharField(max_length=70, null=True)),
                ('region_name', models.CharField(max_length=70, null=True)),
                ('time_zone', models.CharField(max_length=70, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('type_of_attack', models.CharField(blank=True, choices=[('botnet', 'Botnet'), ('Financial fraud', 'Financial Fraud'), ('malware', 'Malware'), ('Phishing', 'Phishing'), ('spam', 'Spam')], max_length=35, null=True)),
            ],
            options={
                'verbose_name': 'Cyber Attack',
                'verbose_name_plural': 'Cyber Attacks',
            },
        ),
        migrations.CreateModel(
            name='CyberVictims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date_time', models.DateField(null=True)),
                ('county', models.CharField(blank=True, choices=[('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Mombasa', 'Mombasa'), ("Murang'a", "Murang'a"), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=45, null=True)),
                ('region', models.CharField(blank=True, choices=[('Coast', 'Coast'), ('Central', 'Central'), ('Lower Eastern', 'Lower Eastern'), ('North Eastern', 'North Eastern'), ('North Rift', 'North Rift'), ('South Rift', 'South Rift'), ('Upper Eastern', 'Upper Eastern'), ('West Kenya', 'West Kenya'), ('Nairobi', 'Nairobi')], max_length=45, null=True)),
                ('address', models.CharField(help_text='Type in the location / place where the         incident occurred in this field. Try to find out the exact location', max_length=50, null=True)),
                ('type_of_attack', models.CharField(blank=True, choices=[('botnet', 'Botnet'), ('Financial fraud', 'Financial Fraud'), ('malware', 'Malware'), ('Phishing', 'Phishing'), ('spam', 'Spam')], max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Cyber Victim',
                'verbose_name_plural': 'Cyber Victims',
            },
        ),
    ]
